version: '3.8'

services:
  pgshard1:
    build:
      context: . 
      dockerfile: Dockerfile
    hostname: pgshard1
    ports:
      - "5432:5432"
    networks:
        - postgresTest
    environment:
      # - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST_AUTH_METHOD=trust

  pgshard2:
    build:
      context: . 
      dockerfile: Dockerfile
    hostname: pgshard2
    ports:
      - "5433:5432"
    networks:
        - postgresTest
    environment:
      # - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgshard3:
    build:
      context: . 
      dockerfile: Dockerfile
    hostname: pgshard3
    ports:
      - "5434:5432"
    networks:
        - postgresTest
    environment:
      # - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pagadmin 
    environment:
      - PGADMIN_DEFAULT_EMAIL=nicopedernera12@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5555:80

networks:
  postgresTest:
  
   

  

